spring.application.name=scheduler

#Spring Batch - false consumes scheduled Trigger
spring.batch.job.enabled = false

#postgres properties
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres?currentSchema=tradingjournal
spring.datasource.username=postgres
spring.datasource.password=1234
#spring.jpa.properties.hibernate.default_schema=tradingjournal
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true

# MongoDB
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=tradingjournal
spring.data.mongodb.username=mongo_user
spring.data.mongodb.password=mongo_password
spring.data.mongodb.authentication-database=admin

# Alternative Mongo URI (full connection string) -> check schema not working
# spring.data.mongodb.uri=mongodb://localhost:27017/