spring.application.name=scheduler

#Spring Batch - false consumes scheduled Trigger
spring.batch.job.enabled = false

#Postgres properties
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres?currentSchema=tradingjournal
spring.datasource.username=postgres
spring.datasource.password=1234
#spring.jpa.properties.hibernate.default_schema=tradingjournal
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true

# MongoDB
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=migration
#spring.data.mongodb.username=mongodb
#spring.data.mongodb.password=1234
#spring.data.mongodb.authentication-database=admin

# Alternative Mongo URI (full connection string) -> check schema not working
# mongodb://localhost:27017/
spring.data.mongodb.uri=mongodb://mongodb:1234@localhost:27017/migration?authSource=admin
